#!/usr/bin/env bash
set -euo pipefail

# KAIRO Fabric Gateway launcher.
# Prefer the real WSL Fabric samples generated by network.sh.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -n "${FABRIC_SAMPLES_DIR:-}" ] && [ -d "$FABRIC_SAMPLES_DIR/test-network/organizations" ]; then
  SAMPLES="$FABRIC_SAMPLES_DIR"
elif [ -d "$HOME/kairo-fabric/fabric-samples/test-network/organizations" ]; then
  SAMPLES="$HOME/kairo-fabric/fabric-samples"
elif [ -d "/mnt/c/Developer/Kairo/fabric/scripts/fabric-samples/test-network/organizations" ]; then
  SAMPLES="/mnt/c/Developer/Kairo/fabric/scripts/fabric-samples"
elif [ -d "$PROJECT_ROOT/work/fabric-samples/test-network/organizations" ]; then
  SAMPLES="$PROJECT_ROOT/work/fabric-samples"
else
  echo "ERROR: Could not locate the generated Fabric samples/organizations tree."
  echo "Expected: $HOME/kairo-fabric/fabric-samples"
  exit 1
fi

ORG="$SAMPLES/test-network/organizations/peerOrganizations/org1.example.com"
USER_MSP="$ORG/users/User1@org1.example.com/msp"
PEER_TLS="$ORG/peers/peer0.org1.example.com/tls/ca.crt"
CERT="$USER_MSP/signcerts/cert.pem"
KEY="$(find "$USER_MSP/keystore" -maxdepth 1 -type f -name '*_sk' -print -quit 2>/dev/null || true)"

if [ ! -f "$CERT" ]; then echo "ERROR: Fabric user certificate not found: $CERT"; exit 1; fi
if [ -z "$KEY" ] || [ ! -f "$KEY" ]; then echo "ERROR: Fabric user private key not found under: $USER_MSP/keystore"; exit 1; fi
if [ ! -f "$PEER_TLS" ]; then echo "ERROR: Fabric peer TLS CA not found: $PEER_TLS"; exit 1; fi

export FABRIC_CHANNEL="${FABRIC_CHANNEL:-mychannel}"
export FABRIC_CHAINCODE="${FABRIC_CHAINCODE:-kairo-trust}"
export FABRIC_MSP_ID="${FABRIC_MSP_ID:-Org1MSP}"
export FABRIC_PEER_ENDPOINT="${FABRIC_PEER_ENDPOINT:-localhost:7051}"
export FABRIC_TLS_HOSTNAME="${FABRIC_TLS_HOSTNAME:-peer0.org1.example.com}"
export FABRIC_CERT="$CERT"
export FABRIC_KEY="$KEY"
export FABRIC_TLS_CERT="$PEER_TLS"
export PORT="${PORT:-8090}"

cd "$PROJECT_ROOT/blockchain-gateway"
npm install --no-audit --no-fund

echo "KAIRO Fabric Gateway configured"
echo "  Samples : $SAMPLES"
echo "  MSP     : $FABRIC_MSP_ID"
echo "  Channel : $FABRIC_CHANNEL"
echo "  Chaincode: $FABRIC_CHAINCODE"
echo "  Endpoint: http://127.0.0.1:$PORT"
node server.js
